In [1]:
import numpy as np
import pandas as pd

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [6]:
import boto3

s3 = boto3.client('s3',
                  endpoint_url='http://localhost:9000',
                  aws_access_key_id='minioadmin',
                  aws_secret_access_key='minioadmin')

# Проверка существования bucket
buckets = s3.list_buckets()
print([b['Name'] for b in buckets['Buckets']])

['arts']

In [2]:
s3.create_bucket(Bucket="arts")

{'ResponseMetadata': {'RequestId': '183C2CCB723138DB',
  'HostId': '',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'accept-ranges': 'bytes',
   'content-length': '0',
   'content-security-policy': 'block-all-mixed-content',
   'location': '/arts',
   'server': 'MinIO',
   'strict-transport-security': 'max-age=31536000; includeSubDomains',
   'vary': 'Origin, Accept-Encoding',
   'x-amz-request-id': '183C2CCB723138DB',
   'x-content-type-options': 'nosniff',
   'x-xss-protection': '1; mode=block',
   'date': 'Sun, 04 May 2025 00:53:27 GMT'},
  'RetryAttempts': 0},
 'Location': '/arts'}

In [8]:
os.getenv('AWS_ACCESS_KEY_ID')

In [5]:
import boto3
import os
from botocore.exceptions import ClientError

try:
    s3 = boto3.client('s3',
                     endpoint_url=os.getenv('MLFLOW_S3_ENDPOINT_URL'),
                     aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
                     aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'))
    print("Available buckets:", s3.list_buckets()['Buckets'])
except ClientError as e:
    print("S3 connection error:", e)
    raise

S3 connection error: An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.

ClientError: An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.

In [2]:
df = pd.read_csv('../data/processed/data_train.csv')
test_raw = pd.read_csv('../data/raw/test.csv')
test = pd.read_csv('../data/processed/test.csv')

test['year'] = pd.to_datetime(test.dates).dt.year
test['week_num'] = pd.to_datetime(test.dates).dt.isocalendar().week
test['month'] = pd.to_datetime(test.dates).dt.month
test['day'] = pd.to_datetime(test.dates).dt.day
test

,dates,SKU,year,week_num,discount,fincode,ui1_code,ui2_code,ui3_code,vendor,brand_code,creation_date,expiration_date,week_num_expiration,year_expiration,week_num_creation,year_creation,month,day
0,2018-12-17,98255,2018,51,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,17
1,2018-12-21,98255,2018,51,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,21
2,2018-12-22,98255,2018,51,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,22
3,2018-12-23,98255,2018,51,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,23
4,2018-12-24,98255,2018,52,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,2019-12-31,80631,2019,1,1.0,15,151,15100,1510003,VWHZMG,WKXRWTP7,2019-05-12,2200-01-01 00:00:00,1,2200,19,2019,12,31
171,2019-12-31,19632,2019,1,1.0,15,151,15100,1510003,UH2WWF,WKXRWTP7,2019-08-19,2200-01-01 00:00:00,1,2200,34,2019,12,31
172,2019-12-31,84395,2019,1,1.0,15,151,15100,1510003,GVL335,WKXRWTP7,2018-04-12,2200-01-01 00:00:00,1,2200,15,2018,12,31
173,2019-12-31,43678,2019,1,1.0,15,151,15100,1510002,VWHZMG,79VL731U,2018-12-13,2200-01-01 00:00:00,1,2200,50,2018,12,31
174,2019-12-31,49661,2019,1,1.0,15,151,15100,1510003,2CI2A8,WKXRWTP7,2019-02-03,2200-01-01 00:00:00,1,2200,5,2019,12,31

In [3]:
df.drop('price_per_sku', axis=1).columns

Index(['dates', 'SKU', 'week_num', 'year', 'discount', 'fincode', 'ui1_code',
       'ui2_code', 'ui3_code', 'vendor', 'brand_code', 'creation_date',
       'expiration_date', 'week_num_expiration', 'year_expiration',
       'week_num_creation', 'year_creation', 'day', 'month'],
      dtype='object')

In [4]:
df

,dates,SKU,price_per_sku,week_num,year,discount,fincode,ui1_code,ui2_code,ui3_code,vendor,brand_code,creation_date,expiration_date,week_num_expiration,year_expiration,week_num_creation,year_creation,day,month
0,2018-01-17,60870,109.182,3,2018,1.0,15,151,15100,1510003,UEYMBB,WKXRWTP7,2018-01-17,2019-04-02 00:00:00,14,2019,3,2018,17,1
1,2018-01-18,60870,109.182,3,2018,1.0,15,151,15100,1510003,UEYMBB,WKXRWTP7,2018-01-17,2019-04-02 00:00:00,14,2019,3,2018,18,1
2,2018-01-19,60870,109.182,3,2018,1.0,15,151,15100,1510003,UEYMBB,WKXRWTP7,2018-01-17,2019-04-02 00:00:00,14,2019,3,2018,19,1
3,2018-01-21,60870,109.182,3,2018,1.0,15,151,15100,1510003,UEYMBB,WKXRWTP7,2018-01-17,2019-04-02 00:00:00,14,2019,3,2018,21,1
4,2018-01-22,60870,109.315,4,2018,1.0,15,151,15100,1510003,UEYMBB,WKXRWTP7,2018-01-17,2019-04-02 00:00:00,14,2019,3,2018,22,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6694,2019-12-23,80631,92.257,52,2019,1.0,15,151,15100,1510003,VWHZMG,WKXRWTP7,2019-05-12,2200-01-01 00:00:00,1,2200,19,2019,23,12
6695,2019-12-23,84395,140.815,52,2019,1.0,15,151,15100,1510003,GVL335,WKXRWTP7,2018-04-12,2200-01-01 00:00:00,1,2200,15,2018,23,12
6696,2019-12-23,38767,74.536,52,2019,1.0,15,151,15100,1510002,4HJSP5,79VL731U,2018-02-08,2200-01-01 00:00:00,1,2200,6,2018,23,12
6697,2019-12-24,49661,165.978,52,2019,1.0,15,151,15100,1510003,2CI2A8,WKXRWTP7,2019-02-03,2200-01-01 00:00:00,1,2200,5,2019,24,12
6698,2019-12-24,10334,101.094,52,2019,1.0,15,151,15100,1510002,4HJSP5,79VL731U,2018-04-19,2200-01-01 00:00:00,1,2200,16,2018,24,12

In [5]:
test

,dates,SKU,year,week_num,discount,fincode,ui1_code,ui2_code,ui3_code,vendor,brand_code,creation_date,expiration_date,week_num_expiration,year_expiration,week_num_creation,year_creation,month,day
0,2018-12-17,98255,2018,51,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,17
1,2018-12-21,98255,2018,51,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,21
2,2018-12-22,98255,2018,51,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,22
3,2018-12-23,98255,2018,51,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,23
4,2018-12-24,98255,2018,52,1.0,15,151,15100,1510002,BLW9FG,79VL731U,2018-07-27,2018-12-26 00:00:00,52,2018,30,2018,12,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,2019-12-31,80631,2019,1,1.0,15,151,15100,1510003,VWHZMG,WKXRWTP7,2019-05-12,2200-01-01 00:00:00,1,2200,19,2019,12,31
171,2019-12-31,19632,2019,1,1.0,15,151,15100,1510003,UH2WWF,WKXRWTP7,2019-08-19,2200-01-01 00:00:00,1,2200,34,2019,12,31
172,2019-12-31,84395,2019,1,1.0,15,151,15100,1510003,GVL335,WKXRWTP7,2018-04-12,2200-01-01 00:00:00,1,2200,15,2018,12,31
173,2019-12-31,43678,2019,1,1.0,15,151,15100,1510002,VWHZMG,79VL731U,2018-12-13,2200-01-01 00:00:00,1,2200,50,2018,12,31
174,2019-12-31,49661,2019,1,1.0,15,151,15100,1510003,2CI2A8,WKXRWTP7,2019-02-03,2200-01-01 00:00:00,1,2200,5,2019,12,31

In [6]:
set(df.drop('price_per_sku', axis=1).columns) == set(test.columns)

True

In [7]:
test.columns

Index(['dates', 'SKU', 'year', 'week_num', 'discount', 'fincode', 'ui1_code',
       'ui2_code', 'ui3_code', 'vendor', 'brand_code', 'creation_date',
       'expiration_date', 'week_num_expiration', 'year_expiration',
       'week_num_creation', 'year_creation', 'month', 'day'],
      dtype='object')

In [8]:
test_raw

          dates    SKU
0    2018-12-17  98255
1    2018-12-21  98255
2    2018-12-22  98255
3    2018-12-23  98255
4    2018-12-24  98255
..          ...    ...
170  2019-12-31  80631
171  2019-12-31  19632
172  2019-12-31  84395
173  2019-12-31  43678
174  2019-12-31  49661

[175 rows x 2 columns]

In [9]:
test_ = pd.merge(test_raw.drop('dates', axis=1), df, on=['SKU', 'year', 'week_num'])
test_

KeyError: 'year'

In [ ]:
test_.columns

**При желании, модель может прогнозировать и спрос, однако в этой задаче мы решаем будем пронозировать цены.**

In [ ]:
#df.drop('num_purchases', axis=1, inplace=True)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df = df.dropna()
df.info()

In [ ]:
test

In [ ]:
df

In [ ]:
df['day'] = pd.to_datetime(df.dates).dt.day
test['day'] = pd.to_datetime(df.dates).dt.day

In [ ]:
df['month'] = pd.to_datetime(df.dates).dt.month
test['month'] = pd.to_datetime(df.dates).dt.month

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
import xgboost as xgb
import optuna
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error
from sklearn.preprocessing import LabelEncoder


X = df.drop(['dates', 'price_per_sku', 'creation_date', 'expiration_date'], axis=1)
y = df.price_per_sku

cat_str_features = ['fincode', 'ui1_code', 'ui2_code', 'ui3_code', 'vendor', 'brand_code']

cat_features = ['year', 'month', 'week_num', 'day']
X_xgb = X.copy()


for col in cat_str_features:
    le = LabelEncoder()
    X_xgb[col] = le.fit_transform(X_xgb[col])
    X_xgb[col] = X_xgb[col].astype('category')

for col in cat_features:
    X_xgb[col] = X_xgb[col].astype('category')

def objective(trial):
    param = {
        'objective': 'reg:squarederror',
        'booster': 'gbtree',
        'eval_metric': 'rmse',
        'verbosity': 0,
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'lambda': trial.suggest_float('lambda', 0.1, 2.0),
        'alpha': trial.suggest_float('alpha', 0.1, 2.0),
        'min_child_weight': trial.suggest_float('min_child_weight', 1, 10),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'gamma': trial.suggest_float('gamma', 0, 1),
        'random_state': RANDOM_STATE
    }
    
    tss = TimeSeriesSplit(10)
    rmse_list = []
    
    for train_index, val_index in tss.split(X_xgb, y):
        X_train, X_val = X_xgb.iloc[train_index], X_xgb.iloc[val_index]
        y_train, y_val = y.iloc[train_index], y.iloc[val_index]
        
        dtrain = xgb.DMatrix(X_train, label=y_train, enable_categorical=True)
        dval = xgb.DMatrix(X_val, label=y_val, enable_categorical=True)
        
        xgb_regressor = xgb.train(param, dtrain, verbose_eval=False)
        y_pred = xgb_regressor.predict(dval)
        
        rmse_list.append(np.sqrt(mean_squared_error(y_val, y_pred)))
        
    return np.mean(rmse_list)

study_xgb = optuna.create_study(direction='minimize')
study_xgb.optimize(objective, n_trials=10)

In [ ]:
X_train_xgb = df.drop(['dates', 'price_per_sku', 'creation_date', 'expiration_date'], axis=1)
y = df.price_per_sku

cat_features = ['year', 'month', 'week_num', 'day']

for col in cat_features:
    X_train_xgb[col] = X_train_xgb[col].astype('category')
    
cat_str_features = ['fincode', 'ui1_code', 'ui2_code', 'ui3_code', 'vendor', 'brand_code']

for col in cat_str_features:
    le = LabelEncoder()
    X_train_xgb[col] = le.fit_transform(X_train_xgb[col])
    X_train_xgb[col] = X_train_xgb[col].astype('category')

dtrain = xgb.DMatrix(X_train_xgb, label=y, enable_categorical=True)

xgb_regressor = xgb.train(study_xgb.best_params, dtrain)

X_inf = test.drop(['dates', 'creation_date', 'expiration_date'], axis=1)
X_inf = X_inf[X_train_xgb.columns]
for col in cat_features:
    X_inf[col] = X_inf[col].astype('category')
    
for col in cat_str_features:
    le = LabelEncoder()
    X_inf[col] = le.fit_transform(X_inf[col])
    X_inf[col] = X_inf[col].astype('category')

dinf = xgb.DMatrix(X_inf, enable_categorical=True)

y_pred = xgb_regressor.predict(dinf)

In [ ]:
test.shape

In [ ]:
test.info()

In [ ]:
test.columns

In [ ]:
X_inf

In [ ]:
y_pred = xgb_regressor.predict(dinf)

In [ ]:
test.loc[:, 'price_per_sku'] = y_pred

In [ ]:
test = test[['dates', 'SKU', 'price_per_sku']]
test

In [ ]:
test.to_csv('../data/processed/submission.csv', index=False)

In [ ]:
xgb_regressor.save_model('../models/xgboost.json')